name: Output Issue Details
on:
  issues:
    types:
      - opened
jobs:
  Fetch-show-details:
    runs-on: ubuntu-latest
    steps:
      - name: Issue details
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "${{ toJson(github.event.issue) }}"
